name: Cron Job

# on:
#   schedule:
#     # Run every 2 minutes
#     - cron: '*/2 * * * *'

on:
  # Trigger manually from Github UI
  workflow_dispatch:

jobs:
  get_request:
    runs-on: ubuntu-latest
    steps:
      - name: Perform POST request
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/660ef9a7ddbbb740ac14d1a8
